# ui
background_opacity      0.85
font_family             CaskaydiaCove Nerd Font Regular
bold_font               CaskaydiaCove Nerd Font Bold
italic_font             CaskaydiaCove Nerd Font Italic
bold_italic_font        CaskaydiaCove Nerd Font Bold Italic
font_size               12
shell                   fish
enable_audio_bell       no
include                 catppuccin-mocha.conf
hide_window_decorations yes
remember_window_size    yes

# shortcut
map f11 toggle_maximized


